name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check disk space before build
        run: |
          echo "=== Disk space before build ==="
          df -h
          echo "=== Docker system info ==="
          docker system df

      - name: Build base Docker image
        run: |
          docker build -t base-env -f base.Dockerfile .
          echo "=== Disk space after base build ==="
          df -h

      - name: Discover and build unit Docker images
        run: |
          # Find all unit directories (unit*, bonus-unit*)
          for unit_dir in unit* bonus-unit*; do
            if [ -d "$unit_dir" ]; then
              echo "=== Processing $unit_dir ==="
              echo "=== Disk space before $unit_dir build ==="
              df -h
              
              # Check if main Dockerfile exists
              if [ -f "$unit_dir/${unit_dir}.Dockerfile" ]; then
                echo "Building main Docker image for $unit_dir"
                cd "$unit_dir"
                docker build -t "${unit_dir}-env" -f "${unit_dir}.Dockerfile" .
                cd ..
              # If main Dockerfile doesn't exist, try scratch version
              elif [ -f "$unit_dir/${unit_dir}_scratch.Dockerfile" ]; then
                echo "Building scratch Docker image for $unit_dir (main not found)"
                cd "$unit_dir"
                docker build -t "${unit_dir}-env" -f "${unit_dir}_scratch.Dockerfile" .
                cd ..
              fi
              
              echo "=== Disk space after $unit_dir build ==="
              df -h
              
              # Remove the unit image to free up space (keep base-env)
              echo "=== Removing ${unit_dir}-env image to free space ==="
              docker rmi "${unit_dir}-env" || echo "Failed to remove ${unit_dir}-env image"
              
              # Clean up Docker system after each build to free space
              echo "=== Cleaning up Docker system ==="
              docker system prune -f
              docker builder prune -f
              echo "=== Disk space after cleanup ==="
              df -h
            fi
          done

      - name: Final disk space check
        run: |
          echo "=== Final disk space ==="
          df -h
          echo "=== Final Docker system info ==="
          docker system df
          