name: Build Docker Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build base Docker image
        run: |
          docker build -t base-env -f base.Dockerfile .

      - name: Discover and build unit Docker images
        run: |
          # Find all unit directories (unit*, bonus-unit*)
          for unit_dir in unit* bonus-unit*; do
            if [ -d "$unit_dir" ]; then
              # Check if main Dockerfile exists
              if [ -f "$unit_dir/${unit_dir}.Dockerfile" ]; then
                echo "Building main Docker image for $unit_dir"
                cd "$unit_dir"
                docker build -t "${unit_dir}-env" -f "${unit_dir}.Dockerfile" .
                cd ..
              # If main Dockerfile doesn't exist, try scratch version
              elif [ -f "$unit_dir/${unit_dir}_scratch.Dockerfile" ]; then
                echo "Building scratch Docker image for $unit_dir (main not found)"
                cd "$unit_dir"
                docker build -t "${unit_dir}-env" -f "${unit_dir}_scratch.Dockerfile" .
                cd ..
              fi
            fi
          done
          